INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MACPROTOCOLS macprotocols)

FIND_PATH(
    MACPROTOCOLS_INCLUDE_DIRS
    NAMES macprotocols/api.h
    HINTS $ENV{MACPROTOCOLS_DIR}/include
        ${PC_MACPROTOCOLS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MACPROTOCOLS_LIBRARIES
    NAMES gnuradio-macprotocols
    HINTS $ENV{MACPROTOCOLS_DIR}/lib
        ${PC_MACPROTOCOLS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MACPROTOCOLS DEFAULT_MSG MACPROTOCOLS_LIBRARIES MACPROTOCOLS_INCLUDE_DIRS)
MARK_AS_ADVANCED(MACPROTOCOLS_LIBRARIES MACPROTOCOLS_INCLUDE_DIRS)

